### PR TITLE
Boot Loader replacement fixes

### PR DESCRIPTION
**Pull request by bspruck**
Replaces the no-very-well-working Boot loader replacement by something which is working for all ROMS, including strange homebrews.

### CODE REVIEW

**Comment by LLeny** [comment]
This closes #11, closes #13

**Comment by twinaphex** [comment]
I still experience crashes running any no-intro roms. Causes a stack dump.  Do I need any BIOS ROM for this to work?

**Comment by bspruck** [comment]
Am 26.01.2016 um 05:18 schrieb Twinaphex:
>
> I still experience crashes running any no-intro roms. Causes a stack
> dump. Do I need any BIOS ROM for this to work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libretro/libretro-handy/pull/16#issuecomment-174812379>.
>
send me the rom

**Comment by twinaphex** [comment]
alright, to your e-mail address?

**Comment by bspruck** [comment]
> alright, to your e-mail address?
>
yeah. you find it on lynxdev.atari.org

just want to verfiy if its headerless or loaderless ;-)

**Comment by Oggom** [comment]
Just gave it a try, No-Intro roms (headerless) do not work.

Also, for some reason this core is stuttering like crazy for me now, but I haven't got the time to see what commit caused that.

**Comment by bspruck** [comment]
Am 26.01.2016 um 17:29 schrieb Oggom:
>
> Just gave it a try, No-Intro roms (headerless) do not work.
>
just to be sure:
no-intro means, plain ROM image without the 64 byte lnx header which
contains the layout information, right?
or does it mean its a lnx file where the encrypted loader is missing
(prototype roms).
the latter one can easily fixed by adding the encryption on
run(load)-time. for copyright reason that would be minimal loader, not
the epyx one, meaning the title picture will not be shown.
>
> Also, for some reason this core is stuttering like crazy for me now,
> but I haven't got the time to see what commit caused that.
>
Can you please check if this happens with lynxboot.img or without? Just
to be sure.


The only difference in the emulation core is the change from 8 bit mono
to 16 bit stereo, which might take older devices over the edge.

**Comment by bspruck** [comment]
> Just gave it a try, No-Intro roms (headerless) do not work.
>
Yeah, I checked it. The file claims to be a lnx rom image (by
extension), but it is not.
Thus, what to you expect.

**Comment by Oggom** [comment]
> no-intro means, plain ROM image without the 64 byte lnx header which contains the layout information, right?

Correct 

> Can you please check if this happens with lynxboot.img or without? Just to be sure. The only difference in the emulation core is the change from 8 bit mono to 16 bit stereo, which might take older devices over the edge.

Happens with and without the BIOS. I assume one of those changes caused some sync issue as the framerates jump around between 56-66fps for me. I can look for the exact commit some time later this week when I've got some free time on my hands. I seriously doubt it's a performance issue.

> Yeah, I checked it. The file claims to be a lnx rom image (by extension), but it is not. Thus, what to you expect.

I am not sure what ROM you've tried, but the only difference between "common" ROM sets and No-Intro ones would be the lack of the previously mentioned headers. Aside from that the files are identical (assuming no bad dumps are involved).

**Comment by bspruck** [comment]
Am 26.01.2016 um 20:34 schrieb Oggom:
> I am not sure what ROM you've tried, but the only difference between
> "common" ROM sets and No-Intro ones would be the lack of the
> previously mentioned headers. Aside from that the files are identical
> (assuming no bad dumps are involved).
Correct. An all lynx emulators derived from handy expect a header to
detect the file type. if no header (magic) is detected, the file is not
loaded. unluckily, this is not a clean exit.
I am still not sure what is now expected. There is no simple way to
detect that a blob of binary data is a valid lynx rom.

PS: I consider a ROM without valid header as broken. thus i do not think
that it should be supported.

**Comment by LLeny** [comment]
I see bspruck's point and tend to agree. 
What is the official policy of libretro on those ROM?

**Comment by twinaphex** [comment]
I think it would be an improvement if those ROMs from those sets could just work. I don't think any technical arguments against or for it make any difference - to the enduser, that this core doesn't load them makes them believe the core is 'broken' and they don't look further.

I also am quite indifferent to all these ROM format wars and I think these wars do more damage than anything else

**Comment by LLeny** [comment]
Yes fair point. Efforts should be made to support any ROM format, it's damaging to the core.
Shouldn't unpackaging, then packaging in a generic format for the cores to support be beneficial? Instead of having all cores dealing with all ROM format themselves.

**Comment by Kivutar** [comment]
I think that the way to go to handle no-intro roms is having an internal database of headers for each rom, like nestopia and mupen are doing it.

Is there such a database maintained somewhere by no-intro?

**Comment by bspruck** [comment]
> I also am quite indifferent to all these ROM format wars and I think 
> these wars do more damage than anything else
>
There is ONE common format for Lynx ROMs. I do not see ANY reason to 
distribute plain dumps without format info.
Supporting that will establish that bad habit.
I would pop up a message on load that the format could not be recognized 
correctly because the header is missing. There are other places where 
you can download the very same ROMs with a valid header. Which means 
sooner or later more will pop up.
Actually I wonder how RetroArch detects that a plain binary ROM image 
belongs to the handy core and not to whatever other system without a header.

Guessing the format of the ROM will work for most (all?) commercial 
games, but fail for most of the post atari (homebrew) releases.
 From the size alone you cannot distinguish between a ROM which uses 128 
block of blocksize 1024 and 256 blocks of blocksize 512. The lnx header 
tells the emulator the blocksize which is (in hardware) the mapping of 
the address lines of the ROM to the pins on the connector.

Maintaining a database. sure. if you find someone. Again I do not see a 
reason for that.

**Comment by Kivutar** [comment]
I totally agree with what you said. Except on one point: "supporting that will establish bad habit". This bad habit is already established, it's called no-intro, and it's very famous and considered as a reference by more and more players everyday, and its popularity have been increasing for years.

They are the only group maintaining a serious database of good dump checksums, and since they did switch to headerless roms for NES and LYNX, there are now a ton of dumps without headers out there.

RetroArch is using their database in its scanning process by checking the roms against the checksum from their db. So when we tell our users to go for no-intro roms, the only dark shadow are those headerless roms. It's a pitty that no-intro took a decision with so much bad consequences.

So now, in RetroArch, we are left 2 choices:

 * Adding external header database in our NES and LYNX emus. Mupen does that already. Nestopia is doing it soon.
 * Rethink our scanning process or more generaly playlist generation, since no-intro is not caring about emulation, but just preservation, maybe it was a poor choice.

**Comment by bspruck** [comment]
Am 27.01.2016 um 09:30 schrieb Jean-André Santoni:
>
> I totally agree with what you said. Except on one point: "supporting 
> that will establish bad habit". This bad habit is already established, 
> it's called no-intro, and it's very famous and considered as a 
> reference by more and more players everyday, and its popularity have 
> been increasing for years.
>
IC
> RetroArch is using their database in its scanning process by checking 
> the roms against the checksum from their db. So when we tell our users 
> to go for no-intro roms, the only dark shadow are those headerless 
> roms. It's a pitty that no-intro took a decision with so much bad 
> consequences.
Preservation is nice, but useless if you do not store how you burn it 
back to a ROM. (in what layout)
Maybe IF they would have preserved the WHOLE address space of the ROM, 
this would be o.k. but then every ROM would be 512kb of size, 
independent of the actual content.
Would be interesting to see how they handled the EPYXs ROMs with 128 
block count.

> So now, in RetroArch, we are left 2 choices:
>
>   * Adding external header database in our NES and LYNX emus. Mupen
>     does that already. Nestopia is doing it soon.
>   * Rethink our scanning process or more generaly playlist generation,
>     since no-intro is not caring about emulation, but just
>     preservation, maybe it was a poor choice.
>

third: I put it in (well, done already) and hope that they will not 
start putting the homebrew ROMs to their famous database.
Still one can pop up a warnign that the header is missing and the core 
is dpdoing its best to guess the layout ;-)

**Comment by vgturtle127** [comment]
@twinaphex @bspruck So is this a bug in Handy? Does Handy not load No-Intro ROMs? I thought most of mine were No-Intro and worked fine...

**Comment by Oggom** [comment]
@vgturtle127 
No-Intro dropped Lynx headers a few years ago. Same with NES.

**Comment by vgturtle127** [comment]
@Oggom Oh, so older versions of a No-Intro collection might have the Lynx headers? That might be why...

**Comment by Kivutar** [comment]
@twinaphex So what about using the DATs from 2003 for Lynx, like we're already doing for NES? While devs are working on implementing support for headerless roms.

**Comment by bspruck** [comment]
> @vgturtle127 <https://github.com/vgturtle127>
> No-Intro dropped Lynx headers a few years ago. Same with NES.
>
Interessting. But they kept the file EXTENSION. Good way to confuse people.

**Comment by twinaphex** [comment]
Actually I'm firmly in the camp that thinks these policies made by No-Intro are rather pointless. Still, they made it a problem anyway for devs to deal with so best we can do now is just jump through the nonsense hoops and get these new romsets working.

**Pull request merged**
