### PR TITLE
adjust sprite pixel timing

### PR DESCRIPTION
**Pull request by trioan**
1 byte = 2 pixels

### CODE REVIEW

**Comment by trioan** [comment]
See https://github.com/libretro/libretro-handy/issues/71

**Comment by trioan** [comment]
Likely going to make some compile-time adjustments. Holding push.

**Comment by twinaphex** [comment]
OK, I'll await further instructions.

**Comment by trioan** [comment]
Going to close this temporarily while I experiment with some other stuff I'm thinking of adding to the core. Then selectively turn it on only for certain ports, as it is a speed hit.

**Pull request closed without merging**
